### ISSUE TITLE
Missing loader?

### ISSUE THREAD

**Issue by matiboy** [matiboy/tuplex-community-server#104]
![image](https://user-images.githubusercontent.com/487758/111743028-07c12c80-88c4-11eb-9514-99f0762f72ad.png)

@mlctrez @HAWX-AUT does anyone know the reason for this being disconnected, and should it be reconnected?

**Comment by HAWX-AUT** [comment]
Hmm dont know. You could try to connect it

**Comment by matiboy** [comment]
ha ha thanks @HAWX-AUT I will simply do that and see what happens.
