### ISSUE TITLE
Recipe change for AAI upgrade

### ISSUE THREAD

**Issue by mlctrez** [matiboy/tuplex-community-server#123]
There are probably other locations where small electric motors are being made but here's the main one:

Green dot in this image:
![image](https://user-images.githubusercontent.com/885489/112576943-550c3500-8dc1-11eb-873f-9f88991abf66.png)

Changes required, see difference between bottom set of factories and top.. remove single cylinder engine assemblers which take iron gears and iron plates, these ingredients now go directly into the small electric motor assembler instead
![image](https://user-images.githubusercontent.com/885489/112576926-4c1b6380-8dc1-11eb-8538-a6514bad9f29.png)

**Comment by mlctrez** [comment]
Big electric motor factory location, green dot on this image:
![image](https://user-images.githubusercontent.com/885489/112577220-f3989600-8dc1-11eb-9bdd-8488508c64d2.png)

Multi cylinder engines from the lower left warehouse were feeding into the two disconnected input belts.  These belts will instead need to be fed steel plate, which needs to be brought in via train

![image](https://user-images.githubusercontent.com/885489/112577344-25116180-8dc2-11eb-9e3c-fa95ad372775.png)

**Comment by mlctrez** [comment]
I'm sure there are mall setups that need to be changed, but this should be fairly straight forward, just switching the requestor chest items.

**Comment by matiboy** [comment]
@mlctrez as I joined the game I saw something about "data formatting" and "efficient data formatting" as well

**Comment by matiboy** [comment]
@mlctrez So basically for the small electric, it skips one step (no more single cylinder, but same ingredients), right?

**Comment by matiboy** [comment]
There happens to be some unused steel plates belts hanging around too

![image](https://user-images.githubusercontent.com/487758/112586217-562b7980-8e36-11eb-9e70-35f4e3b4c6a8.png)

**Comment by mlctrez** [comment]
> @mlctrez So basically for the small electric, it skips one step (no more single cylinder, but same ingredients), right?

Correct.

**Comment by matiboy** [comment]
Steel is ready to be hooked up

**Comment by matiboy** [comment]
All good; closing
