### ISSUE TITLE
Imersite shipping rockets

### ISSUE THREAD

**Issue by matiboy** [matiboy/tuplex-community-server#33]
Ship imersite powder

Reuse rocket set up from vulcanite and holminite

**Comment by mlctrez** [comment]
Rocket setup

**Comment by mlctrez** [comment]
receiving pad and 8 train LTN station setup.. unloading warehouse at top of rocket diamond with previous imersite

**Comment by mlctrez** [comment]
train receiving station below mall setup, provider chest next to spidertrons

**Comment by mlctrez** [comment]
tested end to end 2 rockets launched
