### ISSUE TITLE
Add South copper mine

### ISSUE THREAD

**Issue by matiboy** [matiboy/tuplex-community-server#55]
- complete the huge bridge to the southern island
- add mine
- add hexagon with pick up station
- set up station

**Comment by mlctrez** [comment]
Added 2 lane ( 2 one way 2 the other ) to the hex blueprints book
Setup new mine at 17M copper ore with LTN station

**Comment by mlctrez** [comment]
added mines for 42m and 20m patches

**Comment by matiboy** [comment]
![image](https://user-images.githubusercontent.com/487758/110230575-ec156800-7f4c-11eb-8209-75cc4c8418f2.png)

That should keep us fed for a while. Thanks @mlctrez
