### ISSUE TITLE
Expand Uranium mining

### ISSUE THREAD

**Issue by matiboy** [matiboy/tuplex-community-server#60]
![image](https://user-images.githubusercontent.com/487758/110227516-20305f00-7f34-11eb-9adf-ef5efe6e450a.png)

**Comment by mlctrez** [comment]
Lower right uranium mine is setup via cargo ships. Sulfuric acid is locally produced a bit south.

**Comment by mlctrez** [comment]
All three green circles are setup for mining now.

**Comment by matiboy** [comment]
Thank you!
