### ISSUE TITLE
Uranium u235 rocket to Calidus

### ISSUE THREAD

**Issue by matiboy** [matiboy/tuplex-community-server#62]
- [x] train from nuclear plant to rocket area
- [x] new rocket Limit it to about 10K items
- [x] new landing pad (or use existing one if available)

**Comment by mlctrez** [comment]
Train setup with 16k request and 16k limit in provider
Rocket ships 10k, combinator for green signal and limit on loaded items 
New landing pad setup with passive provider since existing cards have requestor chests

**Comment by matiboy** [comment]
Thanks @mlctrez
