### ISSUE TITLE
Fix polluted U235 train

### ISSUE THREAD

**Issue by matiboy** [matiboy/tuplex-community-server#83]
![image](https://user-images.githubusercontent.com/487758/111116967-cbc75800-85a1-11eb-8bde-08e6b0a66209.png)

Stuck at the station because got some stone?

**Comment by mlctrez** [comment]
Yea, my bad.. I'll fix this after work today.. When I reworked the uranium ore processing, I think some belts got mixed up and stone and iron ore got into the 235 storage.

**Comment by mlctrez** [comment]
Added active provider chests to pull ore out of train.. need to clean up after a few cycles
