### ISSUE TITLE
Move modules factory to Calidus

### ISSUE THREAD

**Issue by matiboy** [matiboy/tuplex-community-server#87]
- [x] Prod 1
 - [x] Prod 2
 - [x] Prod 3
 - [x] Prod 4
 - [x] Prod 5
 - [x] Speed 1
 - [x] Speed 2
 - [x] Speed 3
 - [x] Speed 4
 - [x] Speed 5
 
All in LTN network

**Comment by HAWX-AUT** [comment]
Nauvis factory for T3 is done and shipped. Orbit Manufactory is done. Needs blue Chip delivery from LTN

**Comment by matiboy** [comment]
Thanks a lot! @HAWX-AUT
