### ISSUE TITLE
Tuplex logo with text plates?

### ISSUE THREAD

**Issue by matiboy** [matiboy/tuplex-community-server#89]
![image](https://user-images.githubusercontent.com/487758/111309344-c0a22400-8696-11eb-9e7a-487460bb7277.png)

What if you script added the golden text plate on top ? Thoughts?

**Comment by matiboy** [comment]
Not as nice I guess :/

**Comment by mlctrez** [comment]
I'll have to play around with that a bit. As long as they can be placed in a blueprint with x/y coordinates that should work.

**Comment by matiboy** [comment]
Beautifully done. [Blueprint](https://github.com/matiboy/tuplex-community-server/blob/main/blueprints/tuplex-logo-gold-letters-80x80.txt)
