### ISSUE TITLE
Create cleanup train for cargo parts

### ISSUE THREAD

**Issue by matiboy** [matiboy/tuplex-community-server#93]
So we can put landing pads in places other than the rocket area.

- [ ] dropoff for cargo parts
- [ ] dropoff for capsules
- [ ] dropoff for cargo pods (for crashes)
- [ ] pick up at the Material testing
- [ ] add landing pad for machine learning data at the modules area
- [ ] pick up there

**Comment by mlctrez** [comment]
@matiboy  is this still needed since https://github.com/matiboy/tuplex-community-server/issues/94 is complete?

**Comment by matiboy** [comment]
Not really needed right now, putting on hold
