### ISSUE TITLE
Ship Tier 3 modules to Calidus

### ISSUE THREAD

**Issue by matiboy** [matiboy/tuplex-community-server#94]
@mlctrez I was thinking of moving modules production to Calidus because higher tiers require things from the space station.
Electronic components are annoying to make on Calidus because silicon etc.

Thoughts?

**Comment by mlctrez** [comment]
Yea, I'm considering the same thing for my base.  plus you get better performance per footprint with the space manufactury assemblers

**Comment by matiboy** [comment]
Cool; you ok to set up the rocket for that?

**Comment by matiboy** [comment]
@HAWX-AUT proposed we ship T1 modules instead, I think it's a good idea. Moving to that

**Comment by matiboy** [comment]
And further discussion, we're going to ship T3s

**Comment by HAWX-AUT** [comment]
Shipping is done and solved with smarts. Orbital Module factory still needs building

**Comment by HAWX-AUT** [comment]
Space is also Setup. Only needs blue LTN delivery

**Comment by mlctrez** [comment]
![image](https://user-images.githubusercontent.com/885489/111703384-8f973000-880b-11eb-92e0-001ef01e2518.png)

Nice Setup!

**Comment by matiboy** [comment]
Yup; and blue chips are now hooked up via train on space station too; vitamelange extract delivered by robots

![image](https://user-images.githubusercontent.com/487758/111728838-acce0c00-88a8-11eb-88b8-46b6d96b5329.png)
